config/routes.rb
Rails.application.routes.draw do
  #resources :amazon_orders
  get 'admin/index'
  get 'sessions/new' => 'admin#index'
  get 'sessions/create' => 'admin#index'
  get 'sessions/destroy'
  get 'users/login_path' => 'sessions#new'
  get 'login_path' => 'sessions#new'
  get 'register_url' => 'users#new'
  get 'logout' => 'users#destroy'
  resources :users

  get 'admin' => 'admin#index'
  get 'cash_return' => 'admin#cash_return'
  get 'amazon_orders' => 'admin#amazon_orders'
  get 'daily_rates' => 'admin#daily_rates'
  get 'spiaggia' => 'admin#spiaggia_report'
  get 'properties' => 'admin#properties'
  get 'add_amazon_order' => 'admin#add_amazon_order'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'login' => :destroy
  end

  root 'admin#index'
end

app/models/amazon_order.rb
class AmazonOrder < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_rate.rb
class Daily_Rate < ApplicationRecord
  #has_one :property
end

app/models/expense.rb
class Expense < ApplicationRecord
  has_one :property
  #belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :expenses
  #has_many :daily_rates
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'index', only: [:admin]
  def index
  end

  def cash_return
    @props = Property.joins(:expenses).all
    @expenses = Expense.all
  end

  def amazon_orders
    @table = AmazonOrder.all.sort_by { |a|a[:date]  }
    @list = Array.new
    @table.each do |f|
      if !@list.include?(f[:property])
        @list.push(f[:property])
      end
    end
  end

  def daily_rates
    param1 = params[:param1]
    @properties = Property.all
    if param1 == 'default'
      @daily = nil
    else
      @properties.each do |f|
        if f[:property_address] == param1
          param1 = f[:property_id]
          @current_property = f
        end
      end
      @daily = Daily_Rate.where(:properties_id == param1)
    end
  end

  def add_amazon_order

  end

  def properties
    param1 = params[:param1]
    @flag = false
    if param1 = 'all'
      @properties = Property.all.sort_by { |a|a[:property_address]  }
    else
      @flag = true

    end
  end

  def spiaggia_report

  end
end

app/controllers/amazon_orders_controller.rb
class AmazonOrdersController < ApplicationController
  before_action :set_amazon_order, only: [:show, :edit, :update, :destroy]

  # GET /amazon_orders
  # GET /amazon_orders.json
  def index
    @amazon_orders = AmazonOrder.all
  end

  # GET /amazon_orders/1
  # GET /amazon_orders/1.json
  def show
  end

  # GET /amazon_orders/new
  def new
    @amazon_order = AmazonOrder.new
  end

  # GET /amazon_orders/1/edit
  def edit
  end

  # POST /amazon_orders
  # POST /amazon_orders.json
  def create
    @amazon_order = AmazonOrder.new(amazon_order_params)

    respond_to do |format|
      if @amazon_order.save
        format.html { redirect_to @amazon_order, notice: 'Amazon order was successfully created.' }
        format.json { render :show, status: :created, location: @amazon_order }
      else
        format.html { render :new }
        format.json { render json: @amazon_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amazon_orders/1
  # PATCH/PUT /amazon_orders/1.json
  def update
    respond_to do |format|
      if @amazon_order.update(amazon_order_params)
        format.html { redirect_to @amazon_order, notice: 'Amazon order was successfully updated.' }
        format.json { render :show, status: :ok, location: @amazon_order }
      else
        format.html { render :edit }
        format.json { render json: @amazon_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amazon_orders/1
  # DELETE /amazon_orders/1.json
  def destroy
    @amazon_order.destroy
    respond_to do |format|
      format.html { redirect_to amazon_orders_url, notice: 'Amazon order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amazon_order
      @amazon_order = AmazonOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amazon_order_params
      params.require(:amazon_order).permit(:date, :amount, :double, :number, :property, :desc)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  protected
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Access Denied, Please Log In"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  layout 'new', only: [:login_path]

  def new

  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, alert:'Invalid credentials'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, alert: "Successfully Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :index]
  layout 'new', only: [:register_url]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, alert: "user was successfully created" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, alert: "invalid entry" }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/amazon_orders_helper.rb
module AmazonOrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_dashboard-foot.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment-with-locales.min.js"></script>
<%= javascript_include_tag "lightpick", "calendar-picker" %>
</body>
</html>

app/views/admin/_dashboard-head.html.erb
<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>web_dashboard - Dashboard</title>

  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,600,700" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
  <%= stylesheet_link_tag "styles", "dashboard-content", "lightpick" %>
</head>
<body>

<!-- Navbar -->
<nav>
  <h1>Branding</h1>
  <p>General</p>
  <hr>
  <a href="admin" id="overview">Overview</a>
  <p>Reports</p>
  <hr>
  <a href="cash_return" id="cash_return">Cash Return</a>
  <%= link_to "Daily Rates", daily_rates_path(:param1 => 'default'),:id=>"daily_rates"%>
  <a href="amazon_orders" id="amazon_orders">Amazon Orders</a>
  <a href="spiaggia" id="spiaggia">Spiaggia</a>
  <p>Manage</p>
  <hr>
  <a href="accounts">Accounts</a>
  <%= link_to "Properties", properties_path(:param1 => 'all'),:id=>"properties"%>
  <p>Account</p>
  <hr>
  <a href="settings">Settings</a>
  <a href="logout">Logout</a>
</nav>

<!-- Dashboard Header -->
<!--<header id="header-area">-->
<!--
 <div class="search-bar">-->
<!--    <i class="fas fa-search"></i>-->
<!--    <input type="text" placeholder="Search">-->
<!--  </div>-->
<!--</header>-->

app/views/admin/amazon_orders.html.erb
<%= render 'dashboard-head' %>

<!-- Main Dashboard Content -->
<section class="dashboard-content">
  <!-- Heading -->
  <div class="heading">
    <p>Reports</p>
    <input type="text" id="calendar">
    <h1>Amazon Orders</h1>
    <hr>
  </div>
  <div class="table-container">
    <div class="table-filter">
      <input type="text" placeholder="Filter">
      <label>
        <select name="property-name">
          <option value="none">None</option>
          <% if @list != nil %>
            <% @list.each do |f| %>
                <option><%= f %></option>
            <% end %>
          <% end %>
        </select>
      </label>
      <label>
        <select name="calendar-range">
          <option value="YTD">Year to Date</option>
          <option value="Q1">Quarter 1</option>
          <option value="Q2">Quarter 2</option>
          <option value="Q3">Quarter 3</option>
          <option value="Q4">Quarter 4</option>
        </select>
      </label>
    </div>
    <table>
      <thead>
      <tr>
        <th>Order Date</th>
        <th>Month</th>
        <th>Amount</th>
        <th>Order #</th>
        <th>Property</th>
        <th>Description</th>
      </tr>
      </thead>
      <tbody>
      <% if @table != nil %>
        <% @table.each do |f| %>
          <tr>
            <td><%= f[:date].strftime("%m/%d/%Y") %></td>
            <td><%= f[:date].strftime("%B")%></td>
            <td>$<%= f[:amount] %></td>
            <td><%= f[:number] %></td>
            <td><%= f[:property] %></td>
            <td><%= f[:desc] %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</section>
<script>
    document.getElementById("amazon_orders").className = "active";
</script>
<%= render 'dashboard-foot' %>

app/views/admin/cash_return.html.erb
<%= render 'dashboard-head' %>

<!-- Main Dashboard Content -->
<section class="dashboard-content">
  <!-- Heading -->
  <div class="heading">
    <p>Reports</p>
    <input type="text" id="calendar">
    <h1>Cash Return</h1>
    <hr>
  </div>

  <!-- Foreach Property -->
  <% @props.each do |f| %>
  <div class="table-container">
    <div class="data-container">
      <div class="data-left">
        <p>Purchase Price: <span>$<%= f[:property_purchase_price] %></span></p>
        <p>Loan Amount: <span>$<%= f[:property_loan_amount] %></span></p>
        <p>Cash Investment: <span>$<%= f[:property_cash_investment] %></span></p>
      </div>
      <div class="data-right">
        <p>Updated Value: <span>$<%= f[:property_updated_value] %></span></p>
        <p>Updated LA: <span>$<%= f[:property_updated_loan_amount] %></span></p>
        <p>Equity Adjustment + / -: <span>$<%= f[:property_updated_value] - f[:property_purchase_price] - f[:property_updated_loan_amount] + f[:property_loan_amount] %></span></p>
      </div>
    </div>
    <table>
      <!-- Property Name -->
      <caption><%= f[:property_address] %></caption>
      <thead>
      <tr>
        <th scope="col">Month</th>
        <th scope="col">January</th>
        <th scope="col">February</th>
        <th scope="col">March</th>
        <th scope="col">April</th>
        <th scope="col">May</th>
        <th scope="col">June</th>
        <th scope="col">July</th>
        <th scope="col">August</th>
        <th scope="col">September</th>
        <th scope="col">October</th>
        <th scope="col">November</th>
        <th scope="col">December</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <% add_deposits = Array.new %>
        <th scope="row">Add. Deposit</th>
        <% @expenses.each do |i| %>
          <% if i[:property_id] == f[:property_id] %>
            <%i[:expenses_additional_deposits].each do |x| %>
              <td>$<%= x.round(2) %></td>
              <% add_deposits.push(x) %>
            <% end %>
          <% end %>
        <% end %>
      </tr>

      <tr>
        <% rental_income = Array.new %>
        <th scope="row">Rental Income</th>
        <% @expenses.each do |i| %>
          <% if i[:property_id] == f[:property_id] %>
            <%i[:expenses_rental_income].each do |x| %>
              <td>$<%= x.round(2) %></td>
              <% rental_income.push(x) %>
            <% end %>
          <% end %>
        <% end %>
      </tr>
      <% total_expenses = [0,0,0,0,0,0,0,0,0,0,0,0] %>
      <tr>
        <th scope="row">Monthly Payment</th>
        <% @expenses.each do |i| %>
          <% if i[:property_id] == f[:property_id] %>
            <%i[:expenses_monthly_payment].each_with_index do |val, key|%>
              <td>$<%= val.round(2) %></td>
              <% total_expenses[key] += val %>
            <% end %>
          <% end %>
        <% end %>
      </tr>

      <tr>
        <th scope="row">Other Expenses</th>
        <% @expenses.each do |i| %>
          <% if i[:property_id] == f[:property_id] %>
            <%i[:expenses_other_expenses].each_with_index do |val, key|%>
              <td>$<%= val.round(2) %></td>
              <% total_expenses[key] += val %>
            <% end %>
          <% end %>
        <% end %>
      </tr>

      <tr>
        <th scope="row">Total Expenses</th>
        <% total_expenses.each do |i| %>
              <td>$<%= i.round(2) %></td>
        <% end %>
      </tr>

      <tr>
        <th scope="row">Cash Balance</th>
        <% monthly_amount = Array.new %>
        <% total_expenses.each_with_index do |value, key| %>
          <%if key == 0 %>
            <td>$<%= (add_deposits[key]+ rental_income[key] - total_expenses[key] + 18482.74).round(2) %></td>
            <% monthly_amount.push((add_deposits[key]+ rental_income[key] - total_expenses[key] + 18482.74).round(2)) %>
          <%else %>
            <td>$<%= (add_deposits[key]+ rental_income[key] - total_expenses[key] + monthly_amount[key-1]).round(2) %></td>
            <%monthly_amount.push((add_deposits[key]+ rental_income[key] - total_expenses[key] + monthly_amount[key-1]).round(2)) %>
          <%end %>
        <% end %>
      </tr>

      <tr>
        <th scope="row">Return On Investment</th>
        <% monthly_amount.each_with_index do |val, key| %>
          <%#= monthly_amount[key] %>
          <%#= f[:property_cash_investment] %>
            <td><%= (monthly_amount[key]/f[:property_cash_investment] *100).round(2) %>%</td>
        <% end %>
      </tr>
      </tbody>
    </table>
  </div>
    <% end %>
  <!-- End Foreach -->

</section>
<script>
    document.getElementById("cash_return").className = "active";
</script>
<%= render 'dashboard-foot' %>

app/views/admin/daily_rates.html.erb
<%= render 'dashboard-head' %>
<!-- Main Dashboard Content -->
<section class="dashboard-content">
  <!-- Heading -->
  <div class="heading">
    <p>Reports</p>
    <label>
      <select name="property-name" style="width: 300px">
        <% if @daily == nil %>
          <option value="none" selected>None</option>
          <% @properties.each do |f| %>
            <option><%= f[:property_address] %></option>
          <% end %>
        <% else %>
          <% @properties.each do |f| %>
            <% if @current_property == f %>
              <option selected><%= f[:property_address] %></option>
            <% else %>
              <option><%= f[:property_address] %></option>
            <% end %>
          <% end %>
        <% end %>
      </select>
    </label>
    <h1>Daily Rates</h1>
    <hr>
  </div>
  <% if @daily != nil %>
    <div class="table-container">
      <table>
        <caption><%= @current_property[:property_address] %></caption>
        <thead>
        <tr>
          <th>Dates Booked</th>
          <th>Amount of Days</th>
          <th>Rent</th>
          <th>Daily Rent</th>
        </tr>
        </thead>
        <tbody>
        <!-- Foreach -->
        <% @daily.each do |d| %>
          <% d[:dates_booked].each_with_index do |val, key| %>
            <tr>
              <td><%= val %></td>
              <% start = Date.strptime(val[0,val.index('-')], "%m/%d/%Y")  %>
              <% fin = Date.strptime(val[val.index('-')+1,val.length], "%m/%d/%Y") %>
              <td><%= (fin - start).to_i %></td>
              <td>$<%= @daily[0][:dates_total_rent][key] %></td>
              <td>$<%= @daily[0][:dates_daily_rent][key] %></td>
            </tr>
          <!-- End Foreach-->
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="table-container" style="margin-top: 50px;">
      <table>
        <caption>Actual Occupancy</caption>
        <thead>
        <tr>
          <th>Month</th>
          <th>Total Days</th>
          <th>Days Booked</th>
          <th>Days Available</th>
          <th>Occupancy</th>
        </tr>
        </thead>
        <tbody>
        <!-- Foreach -->
        <tr>
          <td>January</td>
          <td>31</td>
          <td>23</td>
          <td>8</td>
          <!-- days_booked / total_days -->
          <td>74.19%</td>
        </tr>
        <!-- End Foreach-->
        </tbody>
      </table>
    </div>
  <% end %>

</section>
<script>
    $('select').on('change', function() {
        if (this.value === 'none')
            window.location = 'daily_rates?param1=default';
        else
            window.location ='daily_rates?param1=' + this.value;
    });
    document.getElementById("daily_rates").className = "active";
</script>
<%= render 'dashboard-foot' %>

app/views/admin/index.html.erb
<%= render 'dashboard-head' %>

<!-- Main Dashboard Content -->
<section class="dashboard-content">
  <!-- Heading -->
  <div class="heading">
    <p>Dashboard</p>
    <input type="text" id="calendar">
    <h1>Overview</h1>
    <hr>
  </div>
</section>
<script>
    document.getElementById("overview").className = "active";
</script>
<%= render 'dashboard-foot' %>

app/views/admin/properties.html.erb
<%= render 'dashboard-head' %>

<!-- Main Dashboard Content -->
<section class="dashboard-content">
  <!-- Heading -->
  <div class="heading">
    <p>Manage</p>
    <input type="text" id="calendar">
    <h1>Properties</h1>
    <hr>
  </div>
  <div class="card-container">
    <!-- Foreach Property -->
    <% @properties.each do |f| %>
      <div class="card">
        <%= link_to properties_path(:param1 => f[:property_id]),:id=>"properties" do %>
          <img src=<%=f[:property_img] %>>
          <h4><strong><%= f[:property_address] %></strong></h4>
        <% end %>
      </div>
    <% end %>
    <!-- End Foreach -->
  </div>
</section>
<script>
    document.getElementById("properties").className = "active";
</script>
<%= render 'dashboard-foot' %>

app/views/admin/spiaggia_report.html.erb
<%= render 'dashboard-head' %>


<script>
    document.getElementById("spiaggia").className = "active";
</script>
<%= render 'dashboard-foot' %>

app/views/amazon_orders/_form.html.erb
<%= form_with(model: amazon_order, local: true) do |form| %>
  <% if amazon_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amazon_order.errors.count, "error") %> prohibited this amazon_order from being saved:</h2>

      <ul>
      <% amazon_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :double %>
    <%= form.text_field :double %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :property %>
    <%= form.text_field :property %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/amazon_orders/edit.html.erb
<h1>Editing Amazon Order</h1>

<%= render 'form', amazon_order: @amazon_order %>

<%= link_to 'Show', @amazon_order %> |
<%= link_to 'Back', amazon_orders_path %>

app/views/amazon_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Amazon Orders</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Double</th>
      <th>Number</th>
      <th>Property</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amazon_orders.each do |amazon_order| %>
      <tr>
        <td><%= amazon_order.date %></td>
        <td><%= amazon_order.amount %></td>
        <td><%= amazon_order.double %></td>
        <td><%= amazon_order.number %></td>
        <td><%= amazon_order.property %></td>
        <td><%= amazon_order.desc %></td>
        <td><%= link_to 'Show', amazon_order %></td>
        <td><%= link_to 'Edit', edit_amazon_order_path(amazon_order) %></td>
        <td><%= link_to 'Destroy', amazon_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amazon Order', new_amazon_order_path %>

app/views/amazon_orders/new.html.erb
<h1>New Amazon Order</h1>

<%= render 'form', amazon_order: @amazon_order %>

<%= link_to 'Back', amazon_orders_path %>

app/views/amazon_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @amazon_order.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @amazon_order.amount %>
</p>

<p>
  <strong>Double:</strong>
  <%= @amazon_order.double %>
</p>

<p>
  <strong>Number:</strong>
  <%= @amazon_order.number %>
</p>

<p>
  <strong>Property:</strong>
  <%= @amazon_order.property %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @amazon_order.desc %>
</p>

<%= link_to 'Edit', edit_amazon_order_path(@amazon_order) %> |
<%= link_to 'Back', amazon_orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebsiteMaster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>web_dashboard - Login</title>

  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,600,700" rel="stylesheet">
<!--  <link rel="stylesheet" href="../css/login.css">-->
  <%= stylesheet_link_tag "login" %>
</head>
<body>

<div class="container">
  <h1>Branding</h1>
  <p>Dashboard Registration</p>
  <% if flash[:alert] %>
    <p id = 'notice'><%= flash[:alert] %></p>
  <% end %>
  <%= form_with(model: user, local: true, html: {class: "blue"}) do |form| %>
    <%= form.text_field :name, placeholder: "username" %>
    <%= form.password_field :password, placeholder: "password" %>
    <%= form.password_field :password_confirmation, placeholder: "confirm password" %>
    <%= form.submit %>
  <% end %>
  <a href="#password-recovery">Forgot your password?</a>
  <a href= login_path >Have an account? Back to login</a>
</div>
</body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>